# 转发目标URL列表
forward_urls:
  - "https://ai.xxx.cn/api/official/notify"
  - "https://chat.xxx.cn/u/qr_login_callback"

# 服务器配置
host: "0.0.0.0"
port: 8190

# 日志配置
log_file: "forwarder.log"
logging_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL